version: '3.8'

services:
  wallpaper-db:
    build: .
    container_name: wallpaper-db
    ports:
      - "3003:3003"
    volumes:
      - ./public/uploads:/public/uploads
      - ./wallpaper-metadata.json:/wallpaper-metadata.json
    restart: unless-stopped 